# Generated by Django 2.1.7 on 2019-06-02 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
