# Generated by Django 2.1.7 on 2019-06-02 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20190602_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='upload',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.FileExtensionValidator(allowed_extensions=['ppt']), django.core.validators.FileExtensionValidator(allowed_extensions=['pptx'])]),
        ),
    ]
