# Generated by Django 2.1.7 on 2019-06-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20190602_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='date',
            field=models.DateField(),
        ),
    ]
