# Generated by Django 2.1.7 on 2019-06-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20190608_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
