# Generated by Django 2.1.7 on 2019-06-08 16:09

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20190608_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='upload',
            field=models.FileField(upload_to=forms.models.content_file_name),
        ),
    ]
