# Generated by Django 2.1.7 on 2019-06-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20190608_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='filename',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
