# Generated by Django 2.1.7 on 2019-06-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_contactdata_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='delivery',
            field=models.DateField(null=True),
        ),
    ]
